config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  devise_for :users
  namespace :admin do
    resources :users
    resources :tasks
    resources :messages, only: [ :new, :create, :destroy ]
  end
  namespace :client do
    resources :tasks
    resources :messages, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :task
  validates :text_message, length: { maximum: 140 }
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :messages, dependent: :destroy
  belongs_to :user
  validates :description, :name, :status, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :messages, dependent: :destroy
  has_many :tasks, dependent: :destroy
  validates :email, :company, :name, presence: true
end

app/controllers/admin/messages_controller.rb
class Admin::MessagesController < BaseMessagesController
  before_action :authenticate_user!
  before_action do redirect_to root_path unless current_user && current_user.admin end

  def destroy
    @message = Message.find(params[:id])
    if @message.destroy
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/admin/tasks_controller.rb
class Admin::TasksController < BaseTasksController
  before_action :authenticate_user!
  before_action do redirect_to root_path unless current_user && current_user.admin end

  def index
    @tasks = Task.all
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to admin_tasks_path
    end
  end

  def destroy
    @task = Task.find(params[:id])
    if @task.destroy
      redirect_to admin_tasks_path
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action do redirect_to root_path unless current_user && current_user.admin end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_users_path
    else
      render :new
    end
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_users_path
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to admin_users_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :role, :site, :description, :name, :phone, :company)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :admin, :company, :site, :description, :phone, :name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/base_messages_controller.rb
class BaseMessagesController < ApplicationController
  def new
    @message = Message.new
  end

  def create
    @task = Task.find(params[:task_id])
    @message = Message.new(message_params.merge(user: current_user, task: @task))
    if @message.save
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def message_params
    params.require(:message).permit(:text_message)
  end
end

app/controllers/base_tasks_controller.rb
class BaseTasksController < ApplicationController
  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params.merge(user: current_user))
    if @task.save
      redirect_to admin_tasks_path
    else
      render :new
    end
  end

  def show
    @task = Task.find(params[:id])
    @new_message = Message.new
  end

  private
  def task_params
    params.require(:task).permit(:name, :status, :description)
  end
end

app/controllers/client/messages_controller.rb
class Client::MessagesController < BaseMessagesController
  before_action :authenticate_user!
end

app/controllers/client/tasks_controller.rb
class Client::TasksController < BaseTasksController
  before_action :authenticate_user!

  def index
    @tasks = Task.joins(:user).where('users.company = (?)', current_user.company)
  end

  private
  def task_params
    params.require(:task).permit(:name, :status, :description)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout 'auth_form'
  def index
    if user_signed_in?
      @user = current_user
      if current_user.try(:admin)
        redirect_to admin_tasks_path
      else
        redirect_to client_tasks_path
      end
    end
  end
end

app/helpers/admin/messages_helper.rb
module Admin::MessagesHelper
end

app/helpers/admin/tasks_helper.rb
module Admin::TasksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/base_messages_helper.rb
module BaseMessagesHelper
end

app/helpers/base_tasks_helper.rb
module BaseTasksHelper
end

app/helpers/client/messages_helper.rb
module Client::MessagesHelper
end

app/helpers/client/tasks_helper.rb
module Client::TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/tasks/_admin_form.html.erb
<%= simple_form_for( @task, url: admin_tasks_path) do |f| %>
  <%= f.input :name%><br />
  <%= f.input :description %><br />
  <%= f.input :status, ptiority: ["new"], collection: ["new", "visited", "done", "paid", "closed"], include_blank: false %>
  <%= f.button :submit, 'Save' %>
<% end %>

app/views/admin/tasks/edit.html.erb
<%= simple_form_for( @task, url: {action: 'update'}, method: 'PATCH') do |f| %>
  <%= f.input :name%><br />
  <%= f.input :description %><br />
  <%= f.input :status, ptiority: ["new"], collection: ["new", "visited", "done", "paid", "closed"], include_blank: false %>
  <%= f.button :submit, 'Save' %>
<% end %>

app/views/admin/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <thead>
  <tr>
    <th>Task</th>
    <th>Client</th>
    <th>Status</th>
    <th>Description</th>
    <th colspan="4"></th>
  </tr>
  </thead>

  <% @tasks.each do |task| %>
    <tr>
      <td><%= task.name %></td>
      <td><%= task.user.name %></td>
      <td><%= task.status %></td>
      <td><%= task.description %></td>
      <td><%= link_to 'Show', admin_task_path(task) %></td>
      <td><%= link_to 'Edit', edit_admin_task_path(task) %></td>
      <td><%= link_to 'Destroy', admin_task_path(task), method: :delete,
                      data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<br>

<%= link_to 'New Task', new_admin_task_path %>

app/views/admin/tasks/new.html.erb
<%= render 'admin_form' %>

app/views/admin/tasks/show.html.erb
name :<br /> <%= @task.name%>
<br />-----------------------------------------<br />
description :<br /> <%= @task.description %>
<br />-----------------------------------------<br />
status :<br /> <%= @task.status %>
<br />-----------------------------------------<br />
user    :<br /> <%= @task.user.name%>
<br />-----------------------------------------<br />

<br />

Messges<br />
-----------------------------------------<br />
  <% Message.where(task: @task).each do |message| %>
    from : <%= message.user.name %><br />
    text : <%= message.text_message %><br />
    <%= link_to 'Destroy', admin_message_path(message), method: :delete,
                data: { confirm: 'Are you sure?' } %>
  -----------------------------------------<br />
<% end %>


<%= form_for @new_message, url: admin_messages_path do |f| %>
  text : <%= f.text_field :text_message%>
  <%= f.hidden_field_tag(:task_id, @task.id) %>
  <%= f.submit 'Save' %><br />
<% end %>
<br />

app/views/admin/users/_admin_form.html.erb
<%= simple_form_for(@user, url: admin_users_path) do |f| %>
  <%= f.input :email%><br />

  <%= f.input :password%><br />

  <%= f.input :company%><br />

  <%= f.input :name%><br />

  <%= f.input :phone%><br />

  <%= f.input :site%><br />

  <%= f.input :description%><br />

  <%= f.input :admin%><br />

  <%= f.button :submit, 'Save' %>
<% end %>

app/views/admin/users/edit.html.erb
<%= simple_form_for(@user, url: {action: 'update'}, method: 'PATCH') do |f| %>
  <%= f.input :email%><br />

  <%= f.input :company%><br />

  <%= f.input :name%><br />

  <%= f.input :phone%><br />

  <%= f.input :site%><br />

  <%= f.input :description%><br />

  <%= f.input :admin%><br />

  <%= f.button :submit, 'Save' %>
<% end %>

app/views/admin/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
  <tr>
    <th>Email</th>
    <th>Name</th>
    <th>Phone</th>
    <th>Company</th>
    <th colspan="4"></th>
  </tr>
  </thead>

  <% @users.each do |user| %>
    <tr>
      <td><%= user.email %></td>
      <td><%= user.name %></td>
      <td><%= user.phone %></td>
      <td><%= user.company %></td>
      <td><%= link_to 'Show', admin_user_path(user) %></td>
      <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
      <td><%= link_to 'Destroy', admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<br>

<%= link_to 'New User', new_admin_user_path %>

app/views/admin/users/new.html.erb
<%= render 'admin_form' %>

app/views/admin/users/show.html.erb
<%= form_for @user, url: admin_users_path do |f| %>
  email: <%= @user.email%><br />
  company : <%= @user.company %><br />
  description : <%= @user.description %><br />
  name : <%= @user.name %><br />
  phone : <%= @user.phone %><br />
  site : <%= @user.site %><br />
  admin    : <%= @user.admin%><br />
  last visit : <%= @user.last_sign_in_at %>
<% end %>

app/views/client/tasks/_client_form.html.erb
<%= simple_form_for( @task, url: client_tasks_path) do |f| %>
  <%= f.input :name%><br />
  <%= f.input :description %><br />
  <%= f.input :status, ptiority: ["new"], collection: ["new", "visited", "done", "paid", "closed"], include_blank: false %>
  <%= f.button :submit, 'Save' %>
<% end %>

app/views/client/tasks/edit.html.erb
<%= form_for @task, url: {action: 'update'}, method: 'PATCH' do |f| %>
  name : <%= f.text_field :name%><br />
  description : <%= f.text_area :description %><br />
  status    : <%= f.select :status, "<option>new</option>
  <option>visited</option>
  <option>paid</option>
  <option>done</option>
  <option>closed</option>
  ".html_safe, multiple: false %><br />
  <%= f.submit 'Save' %>
<% end %>

app/views/client/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <thead>
  <tr>
    <th>Task</th>
    <th>Client</th>
    <th>Status</th>
    <th>Description</th>
    <th colspan="4"></th>
  </tr>
  </thead>

  <% @tasks.each do |task| %>
    <tr>
      <td><%= task.name %></td>
      <td><%= task.user.name %></td>
      <td><%= task.description %></td>
      <td><%= task.status %></td>
      <td><%= link_to 'Show', client_task_path(task) %></td>
    </tr>
  <% end %>
</table>

<br>

<%= link_to 'New Task', new_client_task_path %>

app/views/client/tasks/new.html.erb
<%= render 'client_form' %>

app/views/client/tasks/show.html.erb
name :<br /> <%= @task.name%>
<br />-----------------------------------------<br />
description :<br /> <%= @task.description %>
<br />-----------------------------------------<br />
status :<br /> <%= @task.status %>
<br />-----------------------------------------<br />
user    :<br /> <%= @task.user.name%>
<br />-----------------------------------------<br />

<br />

Messges<br />
-----------------------------------------<br />
<% Message.where(task: @task).each do |message| %>
  from : <%= message.user.name %><br />
  text : <%= message.text_message %><br />
  -----------------------------------------<br />
<% end %>


<%= form_for @new_message, url: client_messages_path do |f| %>
  text : <%= f.text_field :text_message%>
  <%= f.hidden_field_tag(:task_id, @task.id) %>
  <%= f.submit 'Save' %><br />
<% end %>
<br />

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.input :email %>
  <%= f.input :encrypted_password %>
  <%= f.input :role, priority: [ "users" ], collection: [ "users", "admin" ] %>
  <%= f.button :submit %>
<% end %>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<%= @text %>

app/views/users/new.html.erb
<%= render 'form' %>